# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-24 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('select_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('select_time', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('all_day', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('notification', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('repeat', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('task_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='account.UserProfile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
